sudo: false
# Do not use Travis Python to save some time.
language: generic
env:
  matrix:
  - MYCONDAPY=2.7
  global:
    # ANACONDA_TOKEN encrypted
    secure: "f0JmEc3ggz8y02ZfhWJnaD9YkfQl854xXkEAqobtEJHN9Ism5UqwDBeUCBYLKJ1bdy/sUrWjRb70dRdKb8t/sS943L6Kzr1gA+ZMdGQu/Mmzvstnkvo5Dg98ECUMXoTSyy3v9Xse/cmjFnpkchJus1TPXllWsIVnEfJAP4+56sA="
install:
# Get miniconda. Take the right version, so re-installing python is only needed for 3.5.
- if [[ "$MYCONDAPY" == "2.7" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Get the right python version for building. This only does something for 3.5
- conda install python=${MYCONDAPY}
# Install extra package needed to make things work. Most things can be listed as
# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
- conda install sphinx
# Install conda tools for packaging and uploading
- conda install conda-build anaconda-client
# Add the tovrstra channel to get access to the molmod dependency
- conda config --add channels tovrstra
- conda info -a

# Build the conda package
- conda build -q conda.recipe

# Build source package, should work too and needed for deployment.
- python setup.py sdist

# Install Conda package
- conda install --use-local tamkin

# No visual backend for matplotlib
- mkdir -p ~/.config/matplotlib/
- echo backend:agg > ~/.config/matplotlib/matplotlibrc

# Compile documentation
- (cd doc; make html)
script:
# Run tests out of source tree, to make sure that installed version is tested.
- "(cd; nosetests tamkin -v --processes=2 --detailed-errors --process-timeout=600)"

# Basic code checks
- ./checkwhitespace.py $(find . -type f | egrep '(\.py$)|(\.c$)|(\.pyx$)|(\.pxd$)|(\.h$)|(\.rst$)|(\.in$)|(\.yml$)|(\.yaml$)')

# In deployment, the env var TRAVIS_TAG contains the name of the current tag, if any.
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    # Encrypted github token
    secure: "PpfBEYmfeqmBSwT0qRao3zomXmR50YNbEK7q+VTjk6EJ8hYpt+zxL2IzX12Clsklv7UnPlI/o5OIcwsyFu98B0ptm3SaornShj+4U7Wo5MXaoHSeWrs4IY2XUyV5AkbSCe/d6e25SkiRalZT9jBVtSTTSTGPbN/pzDxeLE9TkCw="
  file: dist/tamkin-${TRAVIS_TAG}.tar.gz
  on:
    repo: molmod/tamkin
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7"
  prerelease: false
- provider: releases
  skip_cleanup: true
  api_key:
    # Encrypted github token
    secure: "PpfBEYmfeqmBSwT0qRao3zomXmR50YNbEK7q+VTjk6EJ8hYpt+zxL2IzX12Clsklv7UnPlI/o5OIcwsyFu98B0ptm3SaornShj+4U7Wo5MXaoHSeWrs4IY2XUyV5AkbSCe/d6e25SkiRalZT9jBVtSTTSTGPbN/pzDxeLE9TkCw="
  file: dist/tamkin-${TRAVIS_TAG}.tar.gz
  on:
    repo: molmod/tamkin
    tags: true
    condition: "$TRAVIS_TAG == *[ab]* && $MYCONDAPY == 2.7"
  prerelease: true
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l alpha ${HOME}/miniconda/conda-bld/linux-64/tamkin-*.tar.bz2
  on:
    repo: molmod/tamkin
    tags: true
    condition: "$TRAVIS_TAG == *a*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l beta ${HOME}/miniconda/conda-bld/linux-64/tamkin-*.tar.bz2
  on:
    repo: molmod/tamkin
    tags: true
    condition: "$TRAVIS_TAG == *b*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l main ${HOME}/miniconda/conda-bld/linux-64/tamkin-*.tar.bz2
  on:
    repo: molmod/tamkin
    tags: true
    condition: "$TRAVIS_TAG != *[ab]*"
- provider: pypi
  skip_cleanup: true
  user: tovrstra
  password:
    # Encrypted PyPI password
    secure: "am4ZKdZzzNbwKd3E9YmVV9H0OFzbmIxVAD4mJL+xqwQrImJyRAlUynoDHXFvMdupJUt4Wdx6IBk9wGume4rqlVMzyd21yQzBVN5ZH2g8MA7sZpEnuLnUQsHv1wT+J0KjwZ+wP/F2B3lvUQNOUbEvRmBfWhum3gH1b9F+0/yTdlY="
  on:
    repo: molmod/tamkin
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7"
- provider: pages
  skip_cleanup: true
  github_token:
    # Encrypted github token
    secure: "PpfBEYmfeqmBSwT0qRao3zomXmR50YNbEK7q+VTjk6EJ8hYpt+zxL2IzX12Clsklv7UnPlI/o5OIcwsyFu98B0ptm3SaornShj+4U7Wo5MXaoHSeWrs4IY2XUyV5AkbSCe/d6e25SkiRalZT9jBVtSTTSTGPbN/pzDxeLE9TkCw="
  project_name: tamkin
  local_dir: doc/_build/html
  on:
    repo: molmod/tamkin
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7"
    tags: true
