sudo: false
language: python
python:
 - "2.7"
branches:
  except:
    # skip version tags
    /^\d+\.\d+(\.\d+)$/
install:
 - pip install --upgrade pip
 - pip install subprocess32 functools32
 - "pip install --only-binary :all: scipy matplotlib cython --upgrade"
 - pip install molmod
 - mkdir -p ~/.config/matplotlib/
 - echo backend:agg > ~/.config/matplotlib/matplotlibrc
 - ./setup.py sdist
script:
 - nosetests -v tamkin --processes=2 --process-timeout=100
