sudo: false
language: python
python:
 - "2.7"
branches:
  except:
    # skip version tags
    /^\d+\.\d+(\.\d+)$/
install:
 - pip install --upgrade pip
 - pip install subprocess32 functools32
 - "pip install --only-binary :all: scipy matplotlib"
 - mkdir -p ~/.config/matplotlib/
 - echo backend:agg > ~/.config/matplotlib/matplotlibrc
 - git clone https://github.com/molmod/molmod.git; cd molmod; python setup.py install; cd ..
script:
 - nosetests -v test --processes=2 --process-timeout=100
